### ISSUE TITLE
Exception - Call to a member function out() on bool

### ISSUE THREAD

**Issue by odeialba** [juacas/moodle-mod_listgrades#6]
I installed the plugin in Moodle 4.3 and Moodle 4.4 and I get the same error in both:
<img width="1512" alt="Error in Moodle 4 3" src="https://github.com/juacas/moodle-mod_listgrades/assets/8805948/4f9ece8c-e26a-4e49-abc0-31bf2d987158">
<img width="1512" alt="Error in Moodle 4 4" src="https://github.com/juacas/moodle-mod_listgrades/assets/8805948/d54ef13f-8db2-47b4-aec7-86e693b8e1e4">

**Comment by juacas** [comment]
It is because there is no site "compact logo" defined in settings.
Nevertheless, this is fixed in v1.0.7

Thanks for reporting.
