### ISSUE TITLE
Error deleting courses.

### ISSUE THREAD

**Issue by sollericos** [juacas/moodle-mod_listgrades#8]
Deleting a course having a listgrades activity throws the following error:

`Call to undefined function listgrades_update_calendar()`

I've added:
* `global $CFG;` to locallib.php (no CFG values were correctly found)
* `require_once("$CFG->dirroot/mod/listgrades/locallib.php");` just before every call to `listgrades_update_calendar();` at lib.php (Maybe it's better one single "require" just at the beginning)
* `global $DB, $CFG;` at the beginning of listgrades_delete_instance() function.

Ciao.

**Comment by juacas** [comment]
Thanks for reporting @sollericos
