### ISSUE TITLE
Error en enlaces al restaurar curso

### ISSUE THREAD

**Issue by minaraja3** [juacas/moodle-mod_listgrades#9]
Hola,

Hemos detectado un problema con el plugin.

Al hacer un backup - restore, donde el restore se hace en un site con el plugin activo, cuando hay enlaces en el curso a páginas de Moodle "/mod/page/view.php?id=", modifica la url a "/mod/listgrades/view.php?id="

Gracias

**Comment by juacas** [comment]
¿Modifica enlaces de otras actividades del curso o solo los enlaces que están incluidos en el texto de la instancia mod_listgrades?

**Comment by minaraja3** [comment]
Me refiero a que tengo etiquetas donde, por ejemplo, hago un índice de contenidos y enlazo a las páginas que tengo en el curso. Al restaurar el curso estos enlaces se han modificado. Si manualmente cambio listgrades por page, vuelve a funcionar. Entonces por algún motivo el plugin ha modificado las urls que van a "/mod/page/view.php?id=", por "/mod/listgrades/view.php?id="

**Comment by juacas** [comment]
El fix está incluido en la release v1.0.9
Muchas gracias por informar.
